version: '3.3'
services:


  iapp-backend:
    image: iapp-backend:latest
    container_name: iapp-backend
    network_mode: bridge
    restart: always
    ports:
      - "8443:8443"
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    network_mode: bridge
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=iApp
      - POSTGRES_SCHEMA=task
    volumes:
       - postgres-data:/var/lib/postgresql/data
        - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    expose:
       - "5432"
    ports:
      - "5432:5432"


volumes:
  postgres-data:


